image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
      
deploy:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - wf10


  

